        // Array de frases
        const frases = [
            "Não é o que acontece com você, mas como você reage que importa.",
            "Nenhuma ansiedade pode mudar o seu futuro.",
            "Seremos odiados tanto por fazer o bem, quanto por fazer o mal.",
            "O tamanho da sua luta revela o tamanho da sua vitória.",
            "A mudança começa no momento em que você decide não ser mais o mesmo.",
            "Às vezes, a maior força reside em manter a calma.",
            "Seja a pessoa que você quer ter na sua vida.",
            "Não subestime o poder de recomeçar.",
            "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
            "A jornada de mil milhas começa com um único passo.",
            "O tempo que você gosta de perder não é tempo perdido.",
            "A verdadeira liberdade é viver sem medo.",
            "O que você pensa, você se torna. O que você sente, você atrai. O que você imagina, você cria.",
            "A felicidade não é algo pronto. Ela vem das suas próprias ações.",
            "Cada dia é uma nova oportunidade para ser melhor.",
            "Não olhe para trás. Você não está indo naquela direção.",
            "Acredite em você mesmo e tudo será possível.",
            "Às vezes, a coisa mais corajosa que você pode fazer é continuar vivendo quando tudo parece dar errado.",
            "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que faz, será bem-sucedido.",
            "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
            "Não importa o quão devagar você vá, desde que você não pare.",
            "Você nunca é velho demais para definir um novo objetivo ou sonhar um novo sonho.",
            "A persistência realiza o impossível.",
            "Só se pode alcançar um grande êxito quando nos mantemos fiéis a nós mesmos.",
            "O caminho para o sucesso sempre está em construção.",
            "Não tenha medo de desacelerar, mas nunca pare.",
            "Grandes coisas nunca vêm de zonas de conforto.",
            "Cada dia é uma página em branco para escrever sua história.",
            "A confiança em si mesmo é o primeiro segredo do sucesso.",
            "A persistência é o menor caminho para o sucesso.",
            "A verdadeira medida do sucesso é o quão feliz você é.",
            "A chave para o sucesso é começar antes que esteja pronto.",
            "Nunca é tarde demais para ser quem você poderia ter sido.",
            "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
            "A disciplina é a ponte entre metas e realizações.",
            "O segredo do sucesso é a constância do propósito.",
            "A diferença entre um sonho e um objetivo é um plano.",
            "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
            "Não importa o quão ocupado você esteja, reserve tempo para fazer algo que ama.",
            "A força não vem do corpo. Vem da vontade da mente.",
            "Grandes mentes discutem ideias; mentes médias discutem eventos; mentes pequenas discutem pessoas.",
            "O maior prazer na vida é fazer aquilo que as pessoas dizem que você não pode fazer.",
            "A única maneira de fazer um excelente trabalho é amar o que você faz.",
            "O sucesso não é o final, o fracasso não é fatal: é a coragem de continuar que conta.",
            "A única coisa que fica entre você e seu objetivo é a história que você continua contando a si mesmo por que não pode alcançá-lo.",
            "Se você quer realizar grandes coisas, você deve primeiro sonhar grandes sonhos.",
            "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
            "A maior realização é viver a vida dos seus sonhos.",
            "Não tenha medo de desistir do bom para perseguir o ótimo.",
            "A melhor maneira de prever o futuro é criá-lo.",
            "O sucesso é gostar de si mesmo, gostar do que você faz e gostar de como você faz isso.",
            "O único modo de fazer um grande trabalho é amar o que você faz.",
            "Não conte os dias, faça com que os dias contem.",
            "Você nunca falhará a menos que desista.",
            "A mudança começa no instante em que você escolhe evoluir.",
            "A força interior é a chama que ilumina o caminho para o sucesso.",
            "Seja a inspiração que você procura nos outros.",
            "Cada desafio é uma oportunidade disfarçada de crescimento.",
            "O sucesso é como uma semente; precisa ser cultivado diariamente.",
            "Não tema o desconhecido, pois é lá que reside a verdadeira descoberta.",
            "A gratidão é a chave que abre a porta para a abundância.",
            "O otimismo é o combustível que impulsiona as conquistas.",
            "A jornada de autodescoberta é a mais valiosa de todas.",
            "Pequenos passos consistentes levam a grandes realizações.",
            "O tempo gasto aprendendo nunca é tempo desperdiçado.",
            "A compaixão é a linguagem universal do coração.",
            "A resiliência é a armadura do guerreiro da vida.",
            "O sorriso é a ponte que conecta corações distantes.",
            "A sabedoria é a luz que dissipa as sombras da ignorância.",
            "A verdadeira riqueza está na abundância de amor e compreensão.",
            "A empatia é a cola que une almas afastadas.",
            "A paciência é a arte de manter a paz interior.",
            "A criatividade é a faísca que acende a inovação.",
            "A coragem é a bússola que aponta para os horizontes infinitos.",
            "A perseverança é a chave mestra que abre todas as portas.",
            "Cada fracasso é um degrau na escada do sucesso.",
            "A autenticidade é a moeda mais valiosa do caráter.",
            "A simplicidade é a sofisticação da alma.",
            "A gentileza é o idioma que todos entendem.",
            "O silêncio é a melodia da introspecção profunda.",
            "A confiança é o alicerce de relacionamentos duradouros.",
            "A compreensão é a cola que une mentes divergentes.",
            "A inovação é a alavanca que move o mundo.",
            "A gratidão transforma o suficiente em mais do que o necessário.",
            "A humildade é a estrela que brilha mais intensamente na escuridão.",
            "A integridade é a bússola que guia na selva da vida.",
            "A alegria é a canção da alma em harmonia com a existência.",
            "A fé é a âncora que mantém firme em meio às tempestades.",
            "A sabedoria é a herança dos que buscam conhecimento constante.",
            "A paciência é a chave que destranca os portões do tempo.",
            "A resiliência é a arte de dançar sob a chuva da adversidade.",
            "A empatia é a poesia escrita com a tinta do coração.",
            "A perseverança é a trilha que leva ao cume da montanha do sucesso.",
            "A mudança começa no instante em que você escolhe evoluir.",
            "A força interior é a chama que ilumina o caminho para o sucesso.",
            "Seja a inspiração que você procura nos outros.",
            "Cada desafio é uma oportunidade disfarçada de crescimento.",
            "O sucesso é como uma semente; precisa ser cultivado diariamente.",
            "Não tema o desconhecido, pois é lá que reside a verdadeira descoberta.",
            "A gratidão é a chave que abre a porta para a abundância.",
            "O otimismo é o combustível que impulsiona as conquistas.",
            "A jornada de autodescoberta é a mais valiosa de todas.",
            "Pequenos passos consistentes levam a grandes realizações.",
            "O tempo gasto aprendendo nunca é tempo desperdiçado.",
            "A compaixão é a linguagem universal do coração.",
            "A resiliência é a armadura do guerreiro da vida.",
            "O sorriso é a ponte que conecta corações distantes.",
            "A sabedoria é a luz que dissipa as sombras da ignorância.",
            "A verdadeira riqueza está na abundância de amor e compreensão.",
            "A empatia é a cola que une almas afastadas.",
            "A paciência é a arte de manter a paz interior.",
            "A criatividade é a faísca que acende a inovação.",
            "A coragem é a bússola que aponta para os horizontes infinitos.",
            "A perseverança é a chave mestra que abre todas as portas.",
            "Cada fracasso é um degrau na escada do sucesso.",
            "A autenticidade é a moeda mais valiosa do caráter.",
            "A simplicidade é a sofisticação da alma.",
            "A gentileza é o idioma que todos entendem.",
            "O silêncio é a melodia da introspecção profunda.",
            "A confiança é o alicerce de relacionamentos duradouros.",
            "A compreensão é a cola que une mentes divergentes.",
            "A inovação é a alavanca que move o mundo.",
            "A gratidão transforma o suficiente em mais do que o necessário.",
            "A humildade é a estrela que brilha mais intensamente na escuridão.",
            "A integridade é a bússola que guia na selva da vida.",
            "A alegria é a canção da alma em harmonia com a existência.",
            "A fé é a âncora que mantém firme em meio às tempestades.",
            "A sabedoria é a herança dos que buscam conhecimento constante.",
            "A paciência é a chave que destranca os portões do tempo.",
            "A resiliência é a arte de dançar sob a chuva da adversidade.",
            "A empatia é a poesia escrita com a tinta do coração.",
            "A perseverança é a trilha que leva ao cume da montanha do sucesso.",
            "A cada novo amanhecer, você tem uma nova chance de alcançar seus sonhos.",
            "Não deixe que as dificuldades de hoje impeçam a realização dos seus objetivos amanhã.",
            "Cada desafio é uma oportunidade para fortalecer sua determinação.",
            "A jornada da vida é cheia de altos e baixos, mas é na persistência que encontramos a verdadeira força.",
            "O caminho para o sucesso é pavimentado com a paciência e a perseverança.",
            "A vitória não é apenas um destino, mas também uma jornada de aprendizado e crescimento.",
            "Não subestime o poder das pequenas vitórias diárias.",
            "A verdadeira força está em continuar mesmo quando tudo parece difícil.",
            "Cada dia que você não desiste é uma vitória sobre as adversidades.",
            "Os sonhos são como sementes, requerem cuidado diário para florescerem.",
            "A jornada para o sucesso é uma maratona, não uma corrida.",
            "Não tema o cansaço, pois cada passo é uma conquista.",
            "A resiliência é a habilidade de se curvar, mas nunca quebrar.",
            "A força não está apenas nos músculos, mas na determinação de seguir em frente.",
            "A paciência é a arte de esperar o momento certo para colher os frutos do seu esforço.",
            "A fé é o combustível que mantém a chama da esperança acesa.",
            "Nunca subestime o impacto positivo de suas ações diárias.",
            "A consistência é a chave para transformar metas em realidade.",
            "Cada obstáculo é uma oportunidade para descobrir sua própria resiliência.",
            "Acredite no poder do processo, não apenas no resultado final.",
            "Você está mais perto do que imagina, continue avançando.",
            "A perseverança é a cola que une a vontade aos resultados.",
            "A positividade é a luz que ilumina o caminho mesmo nas situações mais escuras.",
            "Cada pequeno esforço é um passo em direção à grandeza.",
            "A jornada é tão importante quanto o destino; aprecie cada etapa.",
            "O sucesso não é medido apenas pela linha de chegada, mas pelos desafios superados.",
            "Cada dia é uma oportunidade de renovar sua dedicação aos seus objetivos.",
            "A autenticidade é a base para construir relacionamentos duradouros.",
            "Não tema a lentidão, pois cada passo o aproxima do seu destino.",
            "A determinação é a bússola que aponta na direção dos seus sonhos.",
            "Cada momento de resistência é uma vitória contra a procrastinação.",
            "A motivação pode começar pequena, mas pode levar a conquistas extraordinárias.",
            "O sucesso é a soma de pequenos esforços diários multiplicados ao longo do tempo.",
            "A confiança é construída passo a passo, dia após dia.",
            "A verdadeira grandeza está em continuar tentando, mesmo quando as coisas parecem impossíveis.",
            "Nunca subestime o poder de persistir diante da adversidade.",
            "A autodisciplina é a chave para transformar metas em hábitos.",
            "Cada dia é uma oportunidade de escrever um novo capítulo da sua história de sucesso.",
            "A gratidão pelo presente é o primeiro passo para um futuro abundante.",
            "A determinação transforma obstáculos em trampolins para o sucesso.",
            "A jornada para o sucesso é construída com passos firmes e consistentes.",
            "O progresso é muitas vezes invisível, mas cada passo conta.",
            "A alegria está na jornada tanto quanto no destino.",
            "Cada desafio é uma chance de descobrir o que você é capaz de superar.",
            "A sabedoria está em aprender com cada tentativa, não apenas com os sucessos.",
            "Não desista porque as coisas estão difíceis; lute porque você é mais forte do que os desafios.",
            "A verdadeira vitória está em continuar tentando, independentemente do resultado.",
            "A resiliência transforma contratempos em oportunidades de crescimento.",
            "Cada dia é uma página em branco; escreva uma história que você se orgulhe.",
            "A autenticidade é a chave para construir uma base sólida para o sucesso.",
            "A paciência é a arte de confiar que o tempo revelará o fruto do seu esforço.",
            "Não conte os dias; faça com que cada dia conte em direção aos seus objetivos.",
            "A persistência é a bússola que aponta na direção dos sonhos realizados.",
            "Cada passo é uma dança em direção aos seus objetivos; dance com determinação.",
            "A coragem está em enfrentar o desconhecido, mesmo quando parece assustador.",
            "A autenticidade é a luz que guia nas situações mais escuras.",
            "Cada desafio é uma oportunidade disfarçada para alcançar novas alturas.",
            "A gratidão transforma o suficiente em abundância e o comum em extraordinário.",
            "A paciência é a chave que desbloqueia as portas do tempo e da oportunidade.",
            "O otimismo é a força que impulsiona a jornada rumo às realizações.",
            "A humildade é a estrela que brilha mais intensamente nas noites mais escuras.",
            "A resiliência é a arte de se levantar, mesmo quando tudo parece desmoronar.",
            "A empatia é a ponte que conecta corações, criando laços inquebráveis.",
            "A perseverança é a trilha que leva ao topo da montanha do sucesso.",
            "A mudança começa no momento em que você decide continuar, mesmo quando tudo parece perdido.",
            "A força interior é a luz que ilumina os caminhos mais obscuros.",
            "Seja a inspiração que você procura nos outros; seja a luz que ilumina o caminho.",
            "Cada desafio é uma oportunidade para crescer e se tornar mais forte.",
            "O sucesso é uma semente que precisa ser regada diariamente com esforço e dedicação.",
            "Não tema o desconhecido, pois é lá que reside a verdadeira magia da descoberta.",
            "A gratidão é a chave que abre as portas da abundância e da realização.",
            "O otimismo é o combustível que alimenta a chama das conquistas diárias.",
            "A jornada de autodescoberta é a mais valiosa de todas as jornadas.",
            "Pequenos passos consistentes levam a grandes realizações; celebre cada passo.",
            "O tempo gasto aprendendo nunca é tempo desperdiçado; é um investimento no seu futuro.",
            "A compaixão é a linguagem universal do coração; fale com gentileza.",
            "A resiliência é a armadura que protege o guerreiro da vida nas batalhas diárias.",
            "O sorriso é a ponte que conecta corações distantes; sorria para iluminar o mundo.",
            "A sabedoria é a luz que dissipa as sombras da ignorância; busque o conhecimento constante.",
            "A verdadeira riqueza está na abundância de amor e compreensão; cultive relacionamentos significativos.",
            "A empatia é a cola que une almas afastadas; estenda a mão com compreensão.",
            "A paciência é a arte de manter a paz interior, mesmo em meio à agitação.",
            "A criatividade é a faísca que acende a inovação; pense além dos limites.",
            "A coragem é a bússola que aponta para os horizontes infinitos; siga com bravura.",
            "A perseverança é a chave mestra que abre todas as portas; nunca desista.",
            "Cada fracasso é um degrau na escada do sucesso; aprenda e siga em frente.",
            "A autenticidade é a moeda mais valiosa do caráter; seja verdadeiro consigo mesmo.",
            "A simplicidade é a sofisticação da alma; encontre a beleza na simplicidade.",
            "A gentileza é o idioma que todos entendem; espalhe bondade por onde passar.",
            "O silêncio é a melodia da introspecção profunda; encontre serenidade na quietude.",
            "A confiança é o alicerce de relacionamentos duradouros; construa com honestidade.",
            "A compreensão é a cola que une mentes divergentes; busque a harmonia nas diferenças.",
            "A inovação é a alavanca que move o mundo; ouse criar algo novo.",
            "A gratidão transforma o suficiente em mais do que o necessário; aprecie cada bênção.",
            "A humildade é a estrela que brilha mais intensamente na escuridão; seja humilde em suas conquistas.",
            "A integridade é a bússola que guia na selva da vida; mantenha-se fiel aos seus valores.",
            "A alegria é a canção da alma em harmonia com a existência; encontre alegria em cada momento.",
            "A fé é a âncora que mantém firme em meio às tempestades; confie no seu poder interior.",
            "A sabedoria é a herança dos que buscam conhecimento constante; nunca pare de aprender.",
            "A paciência é a chave que destranca os portões do tempo; aguarde com esperança.",
            "A resiliência é a arte de dançar sob a chuva da adversidade; encontre a beleza na tempestade.",
            "A empatia é a poesia escrita com a tinta do coração; seja gentil com os outros.",
            "A perseverança é a trilha que leva ao cume da montanha do sucesso; continue escalando.",
            "Aceite o que você não pode mudar, tenha coragem para mudar o que pode e sabedoria para distinguir entre eles.",
            "O verdadeiro poder reside em dominar as paixões, não em ser escravo delas.",
            "A felicidade não é encontrada em lugares distantes, mas dentro de você, no controle das suas próprias atitudes.",
            "Viva de acordo com a natureza, pois é nela que encontramos a verdadeira ordem das coisas.",
            "Não espere que os eventos ocorram como você deseja, mas deseje que os eventos ocorram como eles ocorrem, e sua vida será serena.",
            "A vida é breve, o conhecimento é vasto, o tempo é fugaz, o julgamento é difícil.",
            "A verdadeira liberdade é ser indiferente às coisas que não estão em nosso controle.",
            "Aprenda a se contentar com o que tem enquanto busca o que deseja.",
            "O sofrimento nasce da resistência à realidade. Aceite o que é e encontre paz.",
            "Não somos perturbados pelas coisas, mas pela visão que temos delas.",
            "Aprenda a ser solitário, pois nem sempre teremos companhia, exceto a nós mesmos.",
            "O que não está em nosso controle não merece nossa preocupação.",
            "A verdadeira coragem está em enfrentar as adversidades com serenidade e dignidade.",
            "A sabedoria está em não ser escravo dos desejos, mas mestre de si mesmo.",
            "A alegria verdadeira vem de dentro, independente das circunstâncias externas.",
            "Não tema a morte, pois ela é apenas a dissolução dos elementos que compõem seu ser.",
            "A virtude é o único bem verdadeiro; todas as outras coisas são indiferentes.",
            "Aprenda a apreciar as coisas simples da vida; elas são as mais preciosas.",
            "O passado e o futuro são ilusões; o único momento real é o presente.",
            "Não busque a aprovação dos outros; busque a aprovação de sua própria consciência.",
            "A adversidade é a oportunidade para a virtude se destacar.",
            "A verdadeira grandeza está em agir com justiça, bondade e humildade.",
            "A paciência é a chave para superar qualquer obstáculo.",
            "Cultive a indiferença aos prazeres superficiais; encontre alegria na simplicidade.",
            "Não se preocupe com o que os outros dizem ou fazem; preocupe-se com suas próprias ações.",
            "A morte não é o fim, mas uma transformação; abrace-a com serenidade.",
            "O conhecimento é a luz que dissipa as sombras da ignorância.",
            "A verdadeira liberdade está em desapegar-se das coisas materiais.",
            "A verdadeira nobreza está na virtude, não na linhagem.",
            "A sabedoria está em reconhecer a transitoriedade de todas as coisas.",
            "A verdadeira riqueza está na paz interior, não na acumulação de bens.",
            "Aja com retidão, independentemente das consequências.",
            "A humildade é a base sobre a qual se constrói a verdadeira grandeza.",
            "Aprenda a ser forte em sua própria companhia; você é seu melhor amigo.",
            "A verdadeira paz vem de dentro, não do mundo exterior.",
            "Aja com propósito, não por impulso.",
            "A maior virtude está em controlar a língua e as emoções.",
            "A mente tranquila é a fortaleza do sábio.",
            "A felicidade está em viver de acordo com a razão, não com as emoções.",
            "O presente é o único momento real; não o desperdice preocupando-se com o passado ou o futuro.",
            "Aceite a mudança com serenidade; é a única constante na vida.",
            "A verdadeira liberdade está em superar as paixões e desejos.",
            "A verdadeira força está em suportar as adversidades sem perder a dignidade.",
            "A coragem está em enfrentar a verdade, não em fugir dela.",
            "A maior riqueza está na sabedoria, não nas posses materiais.",
            "A verdadeira beleza está na simplicidade e na harmonia.",
            "Aceite as circunstâncias como são, não como você gostaria que fossem.",
            "A verdadeira liberdade é viver de acordo com a razão, não sob o domínio das paixões.",
            "A adversidade é a oportunidade para o aprimoramento da virtude interior.",
            "Não se preocupe com o que está além do seu controle; concentre-se no que você pode influenciar.",
            "A verdadeira riqueza reside na sabedoria acumulada ao longo da jornada.",
            "O conhecimento é a luz que guia através das sombras da ignorância.",
            "Cultive a paciência, pois ela é a chave para superar os obstáculos da vida.",
            "Aja com retidão, mesmo quando enfrentar resistência e desafios.",
            "A felicidade duradoura é encontrada na simplicidade e na aceitação do presente.",
            "A humildade é a pedra angular da verdadeira grandeza de caráter.",
            "Aceite a transitoriedade de todas as coisas e encontre serenidade na mudança.",
            "Aja com propósito, não por impulso momentâneo.",
            "A mente tranquila é a fortaleza do sábio diante das tempestades da vida.",
            "A verdadeira coragem reside em enfrentar a realidade, por mais dura que seja.",
            "A maior virtude está em controlar a língua e as emoções em todas as situações.",
            "Cultive a força interior, pois ela é mais valiosa do que qualquer conquista externa.",
            "A verdadeira paz vem de viver de acordo com a razão, não cedendo às emoções passageiras.",
            "Aceite a mudança com serenidade, pois é a única constante na jornada da vida.",
            "A verdadeira liberdade está em superar as paixões e desejos efêmeros.",
            "A verdadeira força está em suportar as adversidades sem perder a dignidade.",
            "A coragem está em enfrentar a verdade, não em fugir dela.",
            "A maior riqueza está na sabedoria, não nas posses materiais.",
            "A verdadeira beleza está na simplicidade e na harmonia da existência.",
            "Aja com moderação, encontrando equilíbrio em todas as áreas da vida.",
            "Cultive a gratidão, pois ela transforma o suficiente em mais do que o necessário.",
            "A paciência é a chave que destranca os portões do tempo e da oportunidade.",
            "A resiliência é a arte de dançar sob a chuva da adversidade; encontre a beleza na tempestade.",
            "A empatia é a poesia escrita com a tinta do coração; seja gentil com os outros.",
            "A perseverança é a trilha que leva ao cume da montanha do sucesso; continue escalando.",
            "Aceite o que você não pode mudar, tenha coragem para mudar o que pode e sabedoria para distinguir entre eles.",
            "O verdadeiro poder reside em dominar as paixões, não em ser escravo delas.",
            "A felicidade não é encontrada em lugares distantes, mas dentro de você, no controle das suas próprias atitudes.",
            "Viva de acordo com a natureza, pois é nela que encontramos a verdadeira ordem das coisas.",
            "Não espere que os eventos ocorram como você deseja, mas deseje que os eventos ocorram como eles ocorrem, e sua vida será serena.",
            "A vida é breve, o conhecimento é vasto, o tempo é fugaz, o julgamento é difícil.",
            "A verdadeira liberdade é ser indiferente às coisas que não estão em nosso controle.",
            "Aprenda a se contentar com o que tem enquanto busca o que deseja.",
            "O sofrimento nasce da resistência à realidade. Aceite o que é e encontre paz.",
            "Não somos perturbados pelas coisas, mas pela visão que temos delas.",
            "Aprenda a ser solitário, pois nem sempre teremos companhia, exceto a nós mesmos.",
            "O que não está em nosso controle não merece nossa preocupação.",
            "A verdadeira coragem está em enfrentar as adversidades com serenidade e dignidade.",
            "A sabedoria está em não ser escravo dos desejos, mas mestre de si mesmo.",
            "A alegria verdadeira vem de dentro, independente das circunstâncias externas.",
            "Não tema a morte, pois ela é apenas a dissolução dos elementos que compõem seu ser.",
            "A virtude é o único bem verdadeiro; todas as outras coisas são indiferentes.",
            "Aprenda a apreciar as coisas simples da vida; elas são as mais preciosas.",
            "O passado e o futuro são ilusões; o único momento real é o presente.",
            "Não busque a aprovação dos outros; busque a aprovação de sua própria consciência.",
            "A adversidade é a oportunidade para a virtude se destacar.",
            "A verdadeira grandeza está em agir com justiça, bondade e humildade.",
            "A paciência é a chave para superar qualquer obstáculo.",
            "Cultive a indiferença aos prazeres superficiais; encontre alegria na simplicidade.",
            "Não se preocupe com o que os outros dizem ou fazem; preocupe-se com suas próprias ações.",
            "A morte não é o fim, mas uma transformação; abrace-a com serenidade.",
            "O conhecimento é a luz que dissipa as sombras da ignorância.",
            "A verdadeira liberdade está em desapegar-se das coisas materiais.",
            "A verdadeira nobreza está na virtude, não na linhagem.",
            "A sabedoria está em reconhecer a transitoriedade de todas as coisas.",
            "A verdadeira riqueza está na paz interior, não na acumulação de bens.",
            "Aja com retidão, independentemente das consequências.",
            "A humildade é a base sobre a qual se constrói a verdadeira grandeza.",
            "Aprenda a ser forte em sua própria companhia; você é seu melhor amigo.",
            "A verdadeira paz vem de dentro, não do mundo exterior.",
            "Aja com propósito, não por impulso.",
            "A maior virtude está em controlar a mente e as emoções.",
            "Aceite a impermanência da vida com serenidade e gratidão.",
            "A verdadeira liberdade está em transcender as paixões e desejos efêmeros.",
            "A verdadeira força está em suportar as adversidades com dignidade e coragem.",
            "A coragem está em enfrentar a verdade, por mais dura que seja.",
            "A maior riqueza está na sabedoria, não nas posses materiais.",
            "A verdadeira beleza está na simplicidade e na harmonia da existência.",
            "Aja com moderação, encontrando equilíbrio em todas as áreas da vida.",
            "Cultive a gratidão, pois ela transforma o suficiente em mais do que o necessário.",
            "A paciência é a chave que destranca os portões do tempo e da oportunidade.",
            "A resiliência é a arte de dançar sob a chuva da adversidade; encontre a beleza na tempestade.",
            "A empatia é a poesia escrita com a tinta do coração; seja gentil com os outros.",
            "A perseverança é a trilha que leva ao cume da montanha do sucesso; continue escalando.",
            "Aceite o que você não pode mudar, tenha coragem para mudar o que pode e sabedoria para distinguir entre eles.",
            "O verdadeiro poder reside em dominar as paixões, não em ser escravo delas.",
            "A felicidade não é encontrada em lugares distantes, mas dentro de você, no controle das suas próprias atitudes.",
            "Viva de acordo com a natureza, pois é nela que encontramos a verdadeira ordem das coisas.",
            "Não espere que os eventos ocorram como você deseja, mas deseje que os eventos ocorram como eles ocorrem, e sua vida será serena.",
            "A vida é breve, o conhecimento é vasto, o tempo é fugaz, o julgamento é difícil.",
            "A verdadeira liberdade é ser indiferente às coisas que não estão em nosso controle."
        ];

        // Obtém a data atual
        const dataAtual = new Date();

        // Calcula o índice da frase do dia com base na data
        const indiceFraseDoDia = dataAtual.getDate() % frases.length;

        // Exibe a frase correspondente ao dia
        document.getElementById("frase-do-dia").innerHTML = frases[indiceFraseDoDia];